# action.yml
name: 'GTA V Sig Scanner Action'
description: 'This action checks if your build contains bits that are detected by the GTA V sigscanner.'
inputs:
  file:
    description: 'The file to check against GTA V sig database.'
    required: true
outputs:
  detected_string:
    description: 'Output of what is detected.'
  is_detected:
    description: 'Will hold "true" if a something was detected, "false" otherwise.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
